### ISSUE TITLE
clear out any old OSMGeoWeek references

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hot-summit#1] opened 2015-02-12 22:20 UTC
for instance the twitter social media card

**Comment by bgirardot** [comment] 2015-02-14 01:41
I see a number of osmgeoweek in meta data on the layouts/_default.html page
If I knew more about the metadata tag functions I'd fix them myself. I think they are facebook related for likes or shares pulling in data and images to auto create facebook posts.

this url in particular:
http://osmgeoweek.org/img/default-twitter-card.png

**Comment by bgirardot** [comment] 2015-02-14 06:10
I see whats going on here. I'll fix it on Saturday.

**Comment by mikelmaron** [comment] 2015-02-14 15:40
yup, these are mostly for social media shares. for now, we can make the twitter-card a duplicate of the logo?

**Comment by bgirardot** [comment] 2015-02-14 16:18
Yes, I created a duplicate of the logo with dates on it like the osmgeoweek logo had. I'll get it all up here shortly.

**Comment by mikelmaron** [comment] 2015-02-14 16:31
Actually I think @danjoseph has us covered! http://hotosm.github.io/hot-summit/img/default-twitter-card.png   \* Mikel Maron * +14152835207 @mikel s:mikelmaron 

```
 On Saturday, February 14, 2015 8:18 AM, bgirardot <notifications@github.com> wrote:
```

 Yes, I created a duplicate of the logo with dates on it like the osmgeoweek logo had. I'll get it all up here sortly.—

**Comment by bgirardot** [comment] 2015-02-14 16:42
I guess I wasn't watching this repo so that missed those contribs and fixes. My bad. Looks like this issue is ready to close. I will double check osmgeoweek is gone totally in a few minutes.

**Comment by bgirardot** [comment] 2015-02-14 17:34
a grep of gh-pages says there are no more osmgeo week references, I think this can be closed.

**Closed as completed** 2015-02-14 19:53 UTC
